/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'photoBlob' : [] | [ExternalBlob],
  'title' : string,
  'date' : Timestamp,
  'description' : string,
  'memberName' : string,
}
export interface AlumniRecord {
  'id' : bigint,
  'photoBlob' : [] | [ExternalBlob],
  'yearsActive' : string,
  'name' : string,
  'designation' : string,
  'currentStatus' : string,
}
export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'senderPhotoUrl' : string,
  'timestamp' : Timestamp,
  'senderName' : string,
}
export interface CreateAchievementPayload {
  'photoBlob' : [] | [ExternalBlob],
  'title' : string,
  'description' : string,
  'memberName' : string,
}
export interface CreateAlumniPayload {
  'photoBlob' : [] | [ExternalBlob],
  'yearsActive' : string,
  'name' : string,
  'designation' : string,
  'currentStatus' : string,
}
export interface CreateGalleryPhotoPayload {
  'photoBlob' : ExternalBlob,
  'uploaderName' : string,
  'caption' : string,
}
export interface CreateLibraryItemPayload {
  'title' : string,
  'fileBlob' : ExternalBlob,
  'description' : string,
  'category' : string,
}
export interface CreateNoticePayload {
  'title' : string,
  'content' : string,
  'author' : string,
}
export interface Designation {
  'id' : bigint,
  'title' : string,
  'rank' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface GalleryPhoto {
  'id' : bigint,
  'photoBlob' : ExternalBlob,
  'uploadedDate' : Timestamp,
  'uploaderName' : string,
  'caption' : string,
}
export interface LibraryItem {
  'id' : bigint,
  'title' : string,
  'uploadedDate' : Timestamp,
  'fileBlob' : ExternalBlob,
  'description' : string,
  'category' : string,
}
export interface Member {
  'id' : MemberId,
  'photoBlob' : ExternalBlob,
  'status' : MemberStatus,
  'adminSignature' : [] | [string],
  'approvedAt' : [] | [Timestamp],
  'designation' : string,
  'rank' : bigint,
  'rejectionReason' : string,
  'fullName' : string,
  'email' : string,
  'joinReason' : string,
  'phone' : string,
  'fullAddress' : string,
  'registeredAt' : Timestamp,
  'adminNotes' : string,
}
export type MemberId = bigint;
export interface MemberStats {
  'pendingCount' : bigint,
  'total' : bigint,
  'joinedYesterday' : bigint,
  'joinedToday' : bigint,
}
export type MemberStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Notice {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Timestamp,
  'author' : string,
  'archived' : boolean,
}
export interface RegisterMemberPayload {
  'photoBlob' : ExternalBlob,
  'designation' : string,
  'fullName' : string,
  'email' : string,
  'joinReason' : string,
  'phone' : string,
  'fullAddress' : string,
}
export interface SendMessagePayload {
  'text' : string,
  'senderPhotoUrl' : string,
  'senderName' : string,
}
export interface SiteSettings {
  'adminSignature' : string,
  'centerName' : string,
  'siteName' : string,
  'upazilaName' : string,
  'unionName' : string,
}
export type Timestamp = bigint;
export interface UpdateMemberPayload {
  'photoBlob' : ExternalBlob,
  'designation' : string,
  'fullName' : string,
  'email' : string,
  'joinReason' : string,
  'phone' : string,
  'fullAddress' : string,
  'adminNotes' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAchievement' : ActorMethod<[CreateAchievementPayload], Achievement>,
  'addAlumni' : ActorMethod<[CreateAlumniPayload], AlumniRecord>,
  'addDesignation' : ActorMethod<[string, bigint], Designation>,
  'addGalleryPhoto' : ActorMethod<[CreateGalleryPhotoPayload], GalleryPhoto>,
  'addLibraryItem' : ActorMethod<[CreateLibraryItemPayload], LibraryItem>,
  'adminLogin' : ActorMethod<[string], [] | [string]>,
  'approveMember' : ActorMethod<[MemberId, [] | [string]], boolean>,
  'archiveNotice' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNotice' : ActorMethod<[CreateNoticePayload], Notice>,
  'deleteAchievement' : ActorMethod<[bigint], boolean>,
  'deleteAlumni' : ActorMethod<[bigint], boolean>,
  'deleteChatMessage' : ActorMethod<[bigint], boolean>,
  'deleteDesignation' : ActorMethod<[bigint], boolean>,
  'deleteGalleryPhoto' : ActorMethod<[bigint], boolean>,
  'deleteLibraryItem' : ActorMethod<[bigint], boolean>,
  'deleteMember' : ActorMethod<[MemberId], boolean>,
  'deleteNotice' : ActorMethod<[bigint], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getMember' : ActorMethod<[MemberId], [] | [Member]>,
  'getMemberStats' : ActorMethod<[], MemberStats>,
  'getMyMemberProfile' : ActorMethod<[], [] | [Member]>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAchievements' : ActorMethod<[], Array<Achievement>>,
  'listAlumni' : ActorMethod<[], Array<AlumniRecord>>,
  'listDesignations' : ActorMethod<[], Array<Designation>>,
  'listGalleryPhotos' : ActorMethod<[], Array<GalleryPhoto>>,
  'listLibraryItems' : ActorMethod<[], Array<LibraryItem>>,
  'listMembers' : ActorMethod<[], Array<Member>>,
  'listMembersByStatus' : ActorMethod<[MemberStatus], Array<Member>>,
  'listNotices' : ActorMethod<[boolean], Array<Notice>>,
  'registerMember' : ActorMethod<[RegisterMemberPayload], MemberId>,
  'rejectMember' : ActorMethod<[MemberId, string], boolean>,
  'sendChatMessage' : ActorMethod<[SendMessagePayload], ChatMessage>,
  'updateMember' : ActorMethod<[MemberId, UpdateMemberPayload], boolean>,
  'updateMemberDesignation' : ActorMethod<[MemberId, string, bigint], boolean>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'validateAdminSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];