/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateAchievementPayload = IDL.Record({
  'photoBlob' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'memberName' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'photoBlob' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Text,
  'memberName' : IDL.Text,
});
export const CreateAlumniPayload = IDL.Record({
  'photoBlob' : IDL.Opt(ExternalBlob),
  'yearsActive' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'currentStatus' : IDL.Text,
});
export const AlumniRecord = IDL.Record({
  'id' : IDL.Nat,
  'photoBlob' : IDL.Opt(ExternalBlob),
  'yearsActive' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'currentStatus' : IDL.Text,
});
export const Designation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'rank' : IDL.Nat,
});
export const CreateGalleryPhotoPayload = IDL.Record({
  'photoBlob' : ExternalBlob,
  'uploaderName' : IDL.Text,
  'caption' : IDL.Text,
});
export const GalleryPhoto = IDL.Record({
  'id' : IDL.Nat,
  'photoBlob' : ExternalBlob,
  'uploadedDate' : Timestamp,
  'uploaderName' : IDL.Text,
  'caption' : IDL.Text,
});
export const CreateLibraryItemPayload = IDL.Record({
  'title' : IDL.Text,
  'fileBlob' : ExternalBlob,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const LibraryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'uploadedDate' : Timestamp,
  'fileBlob' : ExternalBlob,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const MemberId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateNoticePayload = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Timestamp,
  'author' : IDL.Text,
  'archived' : IDL.Bool,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'senderPhotoUrl' : IDL.Text,
  'timestamp' : Timestamp,
  'senderName' : IDL.Text,
});
export const MemberStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : MemberId,
  'photoBlob' : ExternalBlob,
  'status' : MemberStatus,
  'approvedAt' : IDL.Opt(Timestamp),
  'designation' : IDL.Text,
  'rejectionReason' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'joinReason' : IDL.Text,
  'phone' : IDL.Text,
  'fullAddress' : IDL.Text,
  'registeredAt' : Timestamp,
  'adminNotes' : IDL.Text,
});
export const MemberStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'total' : IDL.Nat,
  'joinedYesterday' : IDL.Nat,
  'joinedToday' : IDL.Nat,
});
export const RegisterMemberPayload = IDL.Record({
  'photoBlob' : ExternalBlob,
  'designation' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'joinReason' : IDL.Text,
  'phone' : IDL.Text,
  'fullAddress' : IDL.Text,
});
export const SendMessagePayload = IDL.Record({
  'text' : IDL.Text,
  'senderPhotoUrl' : IDL.Text,
  'senderName' : IDL.Text,
});
export const UpdateMemberPayload = IDL.Record({
  'photoBlob' : ExternalBlob,
  'designation' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'joinReason' : IDL.Text,
  'phone' : IDL.Text,
  'fullAddress' : IDL.Text,
  'adminNotes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAchievement' : IDL.Func([CreateAchievementPayload], [Achievement], []),
  'addAlumni' : IDL.Func([CreateAlumniPayload], [AlumniRecord], []),
  'addDesignation' : IDL.Func([IDL.Text, IDL.Nat], [Designation], []),
  'addGalleryPhoto' : IDL.Func([CreateGalleryPhotoPayload], [GalleryPhoto], []),
  'addLibraryItem' : IDL.Func([CreateLibraryItemPayload], [LibraryItem], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'approveMember' : IDL.Func([MemberId], [IDL.Bool], []),
  'archiveNotice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNotice' : IDL.Func([CreateNoticePayload], [Notice], []),
  'deleteAchievement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteAlumni' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChatMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteDesignation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGalleryPhoto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLibraryItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMember' : IDL.Func([MemberId], [IDL.Bool], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getMember' : IDL.Func([MemberId], [IDL.Opt(Member)], ['query']),
  'getMemberStats' : IDL.Func([], [MemberStats], ['query']),
  'getMyMemberProfile' : IDL.Func([], [IDL.Opt(Member)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'listAlumni' : IDL.Func([], [IDL.Vec(AlumniRecord)], ['query']),
  'listDesignations' : IDL.Func([], [IDL.Vec(Designation)], ['query']),
  'listGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
  'listLibraryItems' : IDL.Func([], [IDL.Vec(LibraryItem)], ['query']),
  'listMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'listMembersByStatus' : IDL.Func(
      [MemberStatus],
      [IDL.Vec(Member)],
      ['query'],
    ),
  'listNotices' : IDL.Func([IDL.Bool], [IDL.Vec(Notice)], ['query']),
  'registerMember' : IDL.Func([RegisterMemberPayload], [MemberId], []),
  'rejectMember' : IDL.Func([MemberId, IDL.Text], [IDL.Bool], []),
  'sendChatMessage' : IDL.Func([SendMessagePayload], [ChatMessage], []),
  'updateMember' : IDL.Func([MemberId, UpdateMemberPayload], [IDL.Bool], []),
  'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateAchievementPayload = IDL.Record({
    'photoBlob' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'memberName' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'photoBlob' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Text,
    'memberName' : IDL.Text,
  });
  const CreateAlumniPayload = IDL.Record({
    'photoBlob' : IDL.Opt(ExternalBlob),
    'yearsActive' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'currentStatus' : IDL.Text,
  });
  const AlumniRecord = IDL.Record({
    'id' : IDL.Nat,
    'photoBlob' : IDL.Opt(ExternalBlob),
    'yearsActive' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'currentStatus' : IDL.Text,
  });
  const Designation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'rank' : IDL.Nat,
  });
  const CreateGalleryPhotoPayload = IDL.Record({
    'photoBlob' : ExternalBlob,
    'uploaderName' : IDL.Text,
    'caption' : IDL.Text,
  });
  const GalleryPhoto = IDL.Record({
    'id' : IDL.Nat,
    'photoBlob' : ExternalBlob,
    'uploadedDate' : Timestamp,
    'uploaderName' : IDL.Text,
    'caption' : IDL.Text,
  });
  const CreateLibraryItemPayload = IDL.Record({
    'title' : IDL.Text,
    'fileBlob' : ExternalBlob,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const LibraryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'uploadedDate' : Timestamp,
    'fileBlob' : ExternalBlob,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const MemberId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateNoticePayload = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Timestamp,
    'author' : IDL.Text,
    'archived' : IDL.Bool,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'senderPhotoUrl' : IDL.Text,
    'timestamp' : Timestamp,
    'senderName' : IDL.Text,
  });
  const MemberStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : MemberId,
    'photoBlob' : ExternalBlob,
    'status' : MemberStatus,
    'approvedAt' : IDL.Opt(Timestamp),
    'designation' : IDL.Text,
    'rejectionReason' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'joinReason' : IDL.Text,
    'phone' : IDL.Text,
    'fullAddress' : IDL.Text,
    'registeredAt' : Timestamp,
    'adminNotes' : IDL.Text,
  });
  const MemberStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'total' : IDL.Nat,
    'joinedYesterday' : IDL.Nat,
    'joinedToday' : IDL.Nat,
  });
  const RegisterMemberPayload = IDL.Record({
    'photoBlob' : ExternalBlob,
    'designation' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'joinReason' : IDL.Text,
    'phone' : IDL.Text,
    'fullAddress' : IDL.Text,
  });
  const SendMessagePayload = IDL.Record({
    'text' : IDL.Text,
    'senderPhotoUrl' : IDL.Text,
    'senderName' : IDL.Text,
  });
  const UpdateMemberPayload = IDL.Record({
    'photoBlob' : ExternalBlob,
    'designation' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'joinReason' : IDL.Text,
    'phone' : IDL.Text,
    'fullAddress' : IDL.Text,
    'adminNotes' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAchievement' : IDL.Func([CreateAchievementPayload], [Achievement], []),
    'addAlumni' : IDL.Func([CreateAlumniPayload], [AlumniRecord], []),
    'addDesignation' : IDL.Func([IDL.Text, IDL.Nat], [Designation], []),
    'addGalleryPhoto' : IDL.Func(
        [CreateGalleryPhotoPayload],
        [GalleryPhoto],
        [],
      ),
    'addLibraryItem' : IDL.Func([CreateLibraryItemPayload], [LibraryItem], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'approveMember' : IDL.Func([MemberId], [IDL.Bool], []),
    'archiveNotice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNotice' : IDL.Func([CreateNoticePayload], [Notice], []),
    'deleteAchievement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteAlumni' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChatMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteDesignation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGalleryPhoto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLibraryItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMember' : IDL.Func([MemberId], [IDL.Bool], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getMember' : IDL.Func([MemberId], [IDL.Opt(Member)], ['query']),
    'getMemberStats' : IDL.Func([], [MemberStats], ['query']),
    'getMyMemberProfile' : IDL.Func([], [IDL.Opt(Member)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'listAlumni' : IDL.Func([], [IDL.Vec(AlumniRecord)], ['query']),
    'listDesignations' : IDL.Func([], [IDL.Vec(Designation)], ['query']),
    'listGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
    'listLibraryItems' : IDL.Func([], [IDL.Vec(LibraryItem)], ['query']),
    'listMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'listMembersByStatus' : IDL.Func(
        [MemberStatus],
        [IDL.Vec(Member)],
        ['query'],
      ),
    'listNotices' : IDL.Func([IDL.Bool], [IDL.Vec(Notice)], ['query']),
    'registerMember' : IDL.Func([RegisterMemberPayload], [MemberId], []),
    'rejectMember' : IDL.Func([MemberId, IDL.Text], [IDL.Bool], []),
    'sendChatMessage' : IDL.Func([SendMessagePayload], [ChatMessage], []),
    'updateMember' : IDL.Func([MemberId, UpdateMemberPayload], [IDL.Bool], []),
    'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };