/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateAlumniPayload {
    photoBlob?: ExternalBlob;
    yearsActive: string;
    name: string;
    designation: string;
    currentStatus: string;
}
export interface GalleryPhoto {
    id: bigint;
    photoBlob: ExternalBlob;
    uploadedDate: Timestamp;
    uploaderName: string;
    caption: string;
}
export type Timestamp = bigint;
export interface CreateNoticePayload {
    title: string;
    content: string;
    author: string;
}
export interface CreateAchievementPayload {
    photoBlob?: ExternalBlob;
    title: string;
    description: string;
    memberName: string;
}
export interface SendMessagePayload {
    text: string;
    senderPhotoUrl: string;
    senderName: string;
}
export interface RegisterMemberPayload {
    photoBlob: ExternalBlob;
    designation: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type MemberId = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AlumniRecord {
    id: bigint;
    photoBlob?: ExternalBlob;
    yearsActive: string;
    name: string;
    designation: string;
    currentStatus: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Achievement {
    id: bigint;
    photoBlob?: ExternalBlob;
    title: string;
    date: Timestamp;
    description: string;
    memberName: string;
}
export interface ChatMessage {
    id: bigint;
    text: string;
    senderPhotoUrl: string;
    timestamp: Timestamp;
    senderName: string;
}
export interface UpdateMemberPayload {
    photoBlob: ExternalBlob;
    designation: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
    adminNotes: string;
}
export interface SiteSettings {
    adminSignature: string;
    centerName: string;
    siteName: string;
    upazilaName: string;
    unionName: string;
}
export interface Notice {
    id: bigint;
    title: string;
    content: string;
    date: Timestamp;
    author: string;
    archived: boolean;
}
export interface MemberStats {
    pendingCount: bigint;
    total: bigint;
    joinedYesterday: bigint;
    joinedToday: bigint;
}
export interface Member {
    id: MemberId;
    photoBlob: ExternalBlob;
    status: MemberStatus;
    adminSignature?: string;
    approvedAt?: Timestamp;
    designation: string;
    rank: bigint;
    rejectionReason: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
    registeredAt: Timestamp;
    adminNotes: string;
}
export interface LibraryItem {
    id: bigint;
    title: string;
    uploadedDate: Timestamp;
    fileBlob: ExternalBlob;
    description: string;
    category: string;
}
export interface Designation {
    id: bigint;
    title: string;
    rank: bigint;
}
export interface CreateLibraryItemPayload {
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    category: string;
}
export interface CreateGalleryPhotoPayload {
    photoBlob: ExternalBlob;
    uploaderName: string;
    caption: string;
}
export enum MemberStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addAchievement(payload: CreateAchievementPayload): Promise<Achievement>;
    addAlumni(payload: CreateAlumniPayload): Promise<AlumniRecord>;
    addDesignation(title: string, rank: bigint): Promise<Designation>;
    addGalleryPhoto(payload: CreateGalleryPhotoPayload): Promise<GalleryPhoto>;
    addLibraryItem(payload: CreateLibraryItemPayload): Promise<LibraryItem>;
    adminLogin(password: string): Promise<string | null>;
    approveMember(id: MemberId, adminSignature: string | null): Promise<boolean>;
    archiveNotice(id: bigint): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createNotice(payload: CreateNoticePayload): Promise<Notice>;
    deleteAchievement(id: bigint): Promise<boolean>;
    deleteAlumni(id: bigint): Promise<boolean>;
    deleteChatMessage(id: bigint): Promise<boolean>;
    deleteDesignation(id: bigint): Promise<boolean>;
    deleteGalleryPhoto(id: bigint): Promise<boolean>;
    deleteLibraryItem(id: bigint): Promise<boolean>;
    deleteMember(id: MemberId): Promise<boolean>;
    deleteNotice(id: bigint): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getChatMessages(limit: bigint): Promise<Array<ChatMessage>>;
    getMember(id: MemberId): Promise<Member | null>;
    getMemberStats(): Promise<MemberStats>;
    getMyMemberProfile(): Promise<Member | null>;
    getSiteSettings(): Promise<SiteSettings>;
    isCallerAdmin(): Promise<boolean>;
    listAchievements(): Promise<Array<Achievement>>;
    listAlumni(): Promise<Array<AlumniRecord>>;
    listDesignations(): Promise<Array<Designation>>;
    listGalleryPhotos(): Promise<Array<GalleryPhoto>>;
    listLibraryItems(): Promise<Array<LibraryItem>>;
    listMembers(): Promise<Array<Member>>;
    listMembersByStatus(status: MemberStatus): Promise<Array<Member>>;
    listNotices(includeArchived: boolean): Promise<Array<Notice>>;
    registerMember(payload: RegisterMemberPayload): Promise<MemberId>;
    rejectMember(id: MemberId, reason: string): Promise<boolean>;
    sendChatMessage(payload: SendMessagePayload): Promise<ChatMessage>;
    updateMember(id: MemberId, payload: UpdateMemberPayload): Promise<boolean>;
    updateMemberDesignation(id: MemberId, newDesignation: string, newRank: bigint): Promise<boolean>;
    updateSiteSettings(newSettings: SiteSettings): Promise<void>;
    validateAdminSession(token: string): Promise<boolean>;
}
import type { Achievement as _Achievement, AlumniRecord as _AlumniRecord, CreateAchievementPayload as _CreateAchievementPayload, CreateAlumniPayload as _CreateAlumniPayload, CreateGalleryPhotoPayload as _CreateGalleryPhotoPayload, CreateLibraryItemPayload as _CreateLibraryItemPayload, ExternalBlob as _ExternalBlob, GalleryPhoto as _GalleryPhoto, LibraryItem as _LibraryItem, Member as _Member, MemberId as _MemberId, MemberStatus as _MemberStatus, RegisterMemberPayload as _RegisterMemberPayload, Timestamp as _Timestamp, UpdateMemberPayload as _UpdateMemberPayload, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addAchievement(arg0: CreateAchievementPayload): Promise<Achievement> {
        if (this.processError) {
            try {
                const result = await this.actor.addAchievement(await to_candid_CreateAchievementPayload_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Achievement_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAchievement(await to_candid_CreateAchievementPayload_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Achievement_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addAlumni(arg0: CreateAlumniPayload): Promise<AlumniRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlumni(await to_candid_CreateAlumniPayload_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AlumniRecord_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlumni(await to_candid_CreateAlumniPayload_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AlumniRecord_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDesignation(arg0: string, arg1: bigint): Promise<Designation> {
        if (this.processError) {
            try {
                const result = await this.actor.addDesignation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDesignation(arg0, arg1);
            return result;
        }
    }
    async addGalleryPhoto(arg0: CreateGalleryPhotoPayload): Promise<GalleryPhoto> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryPhoto(await to_candid_CreateGalleryPhotoPayload_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GalleryPhoto_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryPhoto(await to_candid_CreateGalleryPhotoPayload_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GalleryPhoto_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async addLibraryItem(arg0: CreateLibraryItemPayload): Promise<LibraryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addLibraryItem(await to_candid_CreateLibraryItemPayload_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_LibraryItem_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLibraryItem(await to_candid_CreateLibraryItemPayload_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_LibraryItem_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveMember(arg0: MemberId, arg1: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMember(arg0, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMember(arg0, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async archiveNotice(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveNotice(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createNotice(arg0: CreateNoticePayload): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(arg0);
            return result;
        }
    }
    async deleteAchievement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAchievement(arg0);
            return result;
        }
    }
    async deleteAlumni(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlumni(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlumni(arg0);
            return result;
        }
    }
    async deleteChatMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatMessage(arg0);
            return result;
        }
    }
    async deleteDesignation(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDesignation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDesignation(arg0);
            return result;
        }
    }
    async deleteGalleryPhoto(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryPhoto(arg0);
            return result;
        }
    }
    async deleteLibraryItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLibraryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLibraryItem(arg0);
            return result;
        }
    }
    async deleteMember(arg0: MemberId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deleteNotice(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getMember(arg0: MemberId): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberStats(): Promise<MemberStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberStats();
            return result;
        }
    }
    async getMyMemberProfile(): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMemberProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMemberProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAchievements();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAchievements();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAlumni(): Promise<Array<AlumniRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlumni();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlumni();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDesignations(): Promise<Array<Designation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDesignations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDesignations();
            return result;
        }
    }
    async listGalleryPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryPhotos();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryPhotos();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLibraryItems(): Promise<Array<LibraryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLibraryItems();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLibraryItems();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembers();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembers();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMembersByStatus(arg0: MemberStatus): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembersByStatus(to_candid_MemberStatus_n44(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembersByStatus(to_candid_MemberStatus_n44(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotices(arg0: boolean): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotices(arg0);
            return result;
        }
    }
    async registerMember(arg0: RegisterMemberPayload): Promise<MemberId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMember(await to_candid_RegisterMemberPayload_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMember(await to_candid_RegisterMemberPayload_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rejectMember(arg0: MemberId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectMember(arg0, arg1);
            return result;
        }
    }
    async sendChatMessage(arg0: SendMessagePayload): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return result;
        }
    }
    async updateMember(arg0: MemberId, arg1: UpdateMemberPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, await to_candid_UpdateMemberPayload_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, await to_candid_UpdateMemberPayload_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMemberDesignation(arg0: MemberId, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberDesignation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberDesignation(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSiteSettings(arg0: SiteSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(arg0);
            return result;
        }
    }
    async validateAdminSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminSession(arg0);
            return result;
        }
    }
}
async function from_candid_Achievement_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Promise<Achievement> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_AlumniRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlumniRecord): Promise<AlumniRecord> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryPhoto_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryPhoto): Promise<GalleryPhoto> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_LibraryItem_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LibraryItem): Promise<LibraryItem> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MemberStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberStatus): MemberStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_Member_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Promise<Member> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Promise<Member | null> {
    return value.length === 0 ? null : await from_candid_Member_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    photoBlob: [] | [_ExternalBlob];
    title: string;
    date: _Timestamp;
    description: string;
    memberName: string;
}): Promise<{
    id: bigint;
    photoBlob?: ExternalBlob;
    title: string;
    date: Timestamp;
    description: string;
    memberName: string;
}> {
    return {
        id: value.id,
        photoBlob: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.photoBlob)),
        title: value.title,
        date: value.date,
        description: value.description,
        memberName: value.memberName
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    photoBlob: [] | [_ExternalBlob];
    yearsActive: string;
    name: string;
    designation: string;
    currentStatus: string;
}): Promise<{
    id: bigint;
    photoBlob?: ExternalBlob;
    yearsActive: string;
    name: string;
    designation: string;
    currentStatus: string;
}> {
    return {
        id: value.id,
        photoBlob: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.photoBlob)),
        yearsActive: value.yearsActive,
        name: value.name,
        designation: value.designation,
        currentStatus: value.currentStatus
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    photoBlob: _ExternalBlob;
    uploadedDate: _Timestamp;
    uploaderName: string;
    caption: string;
}): Promise<{
    id: bigint;
    photoBlob: ExternalBlob;
    uploadedDate: Timestamp;
    uploaderName: string;
    caption: string;
}> {
    return {
        id: value.id,
        photoBlob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.photoBlob),
        uploadedDate: value.uploadedDate,
        uploaderName: value.uploaderName,
        caption: value.caption
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    uploadedDate: _Timestamp;
    fileBlob: _ExternalBlob;
    description: string;
    category: string;
}): Promise<{
    id: bigint;
    title: string;
    uploadedDate: Timestamp;
    fileBlob: ExternalBlob;
    description: string;
    category: string;
}> {
    return {
        id: value.id,
        title: value.title,
        uploadedDate: value.uploadedDate,
        fileBlob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description,
        category: value.category
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MemberId;
    photoBlob: _ExternalBlob;
    status: _MemberStatus;
    adminSignature: [] | [string];
    approvedAt: [] | [_Timestamp];
    designation: string;
    rank: bigint;
    rejectionReason: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
    registeredAt: _Timestamp;
    adminNotes: string;
}): Promise<{
    id: MemberId;
    photoBlob: ExternalBlob;
    status: MemberStatus;
    adminSignature?: string;
    approvedAt?: Timestamp;
    designation: string;
    rank: bigint;
    rejectionReason: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
    registeredAt: Timestamp;
    adminNotes: string;
}> {
    return {
        id: value.id,
        photoBlob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.photoBlob),
        status: from_candid_MemberStatus_n36(_uploadFile, _downloadFile, value.status),
        adminSignature: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.adminSignature)),
        approvedAt: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.approvedAt)),
        designation: value.designation,
        rank: value.rank,
        rejectionReason: value.rejectionReason,
        fullName: value.fullName,
        email: value.email,
        joinReason: value.joinReason,
        phone: value.phone,
        fullAddress: value.fullAddress,
        registeredAt: value.registeredAt,
        adminNotes: value.adminNotes
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): MemberStatus {
    return "pending" in value ? MemberStatus.pending : "approved" in value ? MemberStatus.approved : "rejected" in value ? MemberStatus.rejected : value;
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Promise<Array<Achievement>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Achievement_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlumniRecord>): Promise<Array<AlumniRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AlumniRecord_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryPhoto>): Promise<Array<GalleryPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryPhoto_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LibraryItem>): Promise<Array<LibraryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LibraryItem_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Promise<Array<Member>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Member_n34(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateAchievementPayload_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateAchievementPayload): Promise<_CreateAchievementPayload> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateAlumniPayload_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateAlumniPayload): Promise<_CreateAlumniPayload> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateGalleryPhotoPayload_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGalleryPhotoPayload): Promise<_CreateGalleryPhotoPayload> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateLibraryItemPayload_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLibraryItemPayload): Promise<_CreateLibraryItemPayload> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MemberStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): _MemberStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
async function to_candid_RegisterMemberPayload_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterMemberPayload): Promise<_RegisterMemberPayload> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateMemberPayload_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMemberPayload): Promise<_UpdateMemberPayload> {
    return await to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photoBlob?: ExternalBlob;
    yearsActive: string;
    name: string;
    designation: string;
    currentStatus: string;
}): Promise<{
    photoBlob: [] | [_ExternalBlob];
    yearsActive: string;
    name: string;
    designation: string;
    currentStatus: string;
}> {
    return {
        photoBlob: value.photoBlob ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.photoBlob)) : candid_none(),
        yearsActive: value.yearsActive,
        name: value.name,
        designation: value.designation,
        currentStatus: value.currentStatus
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photoBlob: ExternalBlob;
    uploaderName: string;
    caption: string;
}): Promise<{
    photoBlob: _ExternalBlob;
    uploaderName: string;
    caption: string;
}> {
    return {
        photoBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.photoBlob),
        uploaderName: value.uploaderName,
        caption: value.caption
    };
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    category: string;
}): Promise<{
    title: string;
    fileBlob: _ExternalBlob;
    description: string;
    category: string;
}> {
    return {
        title: value.title,
        fileBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description,
        category: value.category
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photoBlob: ExternalBlob;
    designation: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
}): Promise<{
    photoBlob: _ExternalBlob;
    designation: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
}> {
    return {
        photoBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.photoBlob),
        designation: value.designation,
        fullName: value.fullName,
        email: value.email,
        joinReason: value.joinReason,
        phone: value.phone,
        fullAddress: value.fullAddress
    };
}
async function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photoBlob: ExternalBlob;
    designation: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
    adminNotes: string;
}): Promise<{
    photoBlob: _ExternalBlob;
    designation: string;
    fullName: string;
    email: string;
    joinReason: string;
    phone: string;
    fullAddress: string;
    adminNotes: string;
}> {
    return {
        photoBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.photoBlob),
        designation: value.designation,
        fullName: value.fullName,
        email: value.email,
        joinReason: value.joinReason,
        phone: value.phone,
        fullAddress: value.fullAddress,
        adminNotes: value.adminNotes
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photoBlob?: ExternalBlob;
    title: string;
    description: string;
    memberName: string;
}): Promise<{
    photoBlob: [] | [_ExternalBlob];
    title: string;
    description: string;
    memberName: string;
}> {
    return {
        photoBlob: value.photoBlob ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.photoBlob)) : candid_none(),
        title: value.title,
        description: value.description,
        memberName: value.memberName
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == MemberStatus.pending ? {
        pending: null
    } : value == MemberStatus.approved ? {
        approved: null
    } : value == MemberStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
